#!/usr/bin/env bash

export ProjectRoot=$(pwd)

clean() {
  echo Cleaning output folders...
  echo
  rm -rf bin/d* include/d* lib/*
}

build() {
  cd build/run
  cmake ../..
  make -j 12
  make install | egrep -v 'gmock|gtest'
  cd ${ProjectRoot}
}

tests() {
  if [[ -f bin/asdf_tests ]]; then
    echo && ./bin/asdf_tests
  else
    printf "${bldred}Can't find installed executable ${bldylw}bin/asdf_tests.${clr}\n"
    exit 2
  fi
}

main() {
  build
  tests
}

main
